apiVersion: apps/v1
kind: Deployment
metadata:
  name: wealthcare-monolith-app
  namespace: wealthcare-monolith-ns
  labels:
    app: wealthcare-app
    subname: monolith
spec:
  selector:
    matchLabels:
      app: wealthcare-app
      subname: monolith
  replicas: 30
  template:
    metadata:
      labels:
        app: wealthcare-app
        subname: monolith    
    spec:
      containers:
        - name: container-monolith
          image: "default-route-openshift-image-registry.apps.cluster-r8mzp.r8mzp.sandbox2398.opentlc.com/wealthcare-monolith-ns/wealthcare-monolith-ocp-oss:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: 9080-tcp
              containerPort: 9080
              protocol: TCP
            - name: https
              containerPort: 9443
          resources:
            requests:
              memory: "25Mi"
              cpu: "25m"
            limits:
              memory: "50Mi"
              cpu: "50m"                  
          envFrom:
            - configMapRef:
                name: wealthcare-monolith-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: wealthcare-monolith-app
  namespace: wealthcare-monolith-ns
  labels:
    app: wealthcare-app
    subname: monolith
spec:
  type: LoadBalancer
  ports:
    - name: 9080-tcp
      port: 9080
      targetPort: 9080
  selector:
    app: wealthcare-app
    subname: monolith
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wealthcare-monolith-app
  namespace: wealthcare-monolith-ns
  labels:
    app: wealthcare-app
    subname: monolith
spec:
  path: /
  to:
    kind: Service
    name: wealthcare-monolith-app
    weight: 100
  port:
    targetPort: 9080-tcp
